export const AppRoutes = {
    splash: "SaplashScreen",
    signIn: "SignIn",
    password: "PasswordScreen",
    createAccount: "CreateAccount",
    forgetPassword: "ForgetPassword",
    homepage: "HomePage",
    categories: "Categories",
    hoodies: "Hoodies",
    detail: "DetailScreen",
    notification: "NotificationScreen",
    order: "OrderScreen",
    profile: "ProfilScreen",
    bottomTabs: "bottomTabs",
    stackTab: "StackTab",
    address: "AddressScreen",
    addressTextScreen: "AddressTextScreen",
    seeAll: "SeeAllItems",
    hoodiesScreen:"HoodieScreen",
    exploreNotification:"ExploreNotification",
    exploreOrder:"ExploreOrder",
}
