const AppStrings = {
    signin: "Sign in",
    emailAddress: "Email Address",
    password: "Password",
    continue: "Continue",
    anAccount: "Dont have an Account ?",
    createOne: " Create One",
    apple: "Continue With Apple",
    google: "Continue With Google",
    facebook: "Continue With Facebook",
    Password: "Password",
    forgotPassword: "Forgot Password ?",
    reset: " Reset",
    createAccount: "Create Account",
    firstname: "Firstname",
    lastName: "Lastname",
    enterEmailAddress: "Enter Email address",
    resetPasswordTitle: "We Sent you an Email to reset your password.",
    ReturntoLogin: "Return to Login",
    yourSelf: "Tell us About yourself",
    shop: "Who do you shop for ?",
    women: "Women",
    men: "Men",
    howOld: "How Old are you ?",
    ageRange: "Age Range",
    finish: "Finish",
    Categories: "Categories",
    shopCategories: "Shop by Categories",
    Hoodies: "Hoodies",
    hoodies240: "Hoodies (240)",
    noNotification: "No Notification yet",
    exploreCategories: "Explore Categories",
    notiText: "Gilbert, you placed and order check your \n order history for full details",
    thankYou: "Gilbert, Thank you for shopping with us we have canceled order #24568.",
    orderText: "Gilbert, your Order #24568 has been  confirmed check  your order history for full details",
    ordersTitle: "Orders",
    noOrdersyet: "No Orders yet",
    Search: "Search",
    SeeAll: "See All",
    shorts: "Shorts",
    shoes: "Shoes",
    bag: "Bag",
    accessories: "Accessories",
    topSelling: "Top Selling",
    menHarringtonJacket: "Men's Harrington Jacket",
    priceJacket: 148.00,
    maxCirro: "Max Cirro Men's Slides",
    priceMaxCirro: 55.00,
    description: "Built for life and made to last, this full-zip corduroy jacket is part of our Nike Life collection. The spacious fit gives you plenty of room to layer underneath, while the soft corduroy keeps it casual and timeless.",
    pullOverHoodie: "Men's Ice-Dye Pullover Hoodie",
    priceOver: 128.97,
    pullOverJakect: "Men's Fleece Pullover Hoodie",
    fleecePrice: 100.00,
    skateHoodie: "Fleece Pullover Skate Hoodie",
    priceSkate: 150.97,
    yellowHoodies: "Fleece Skate Hoodie",
    priceYellow: 110.00,
    shippingReturns: "Shipping & Returns",
    GilbertJones:"Gilbert Jones",
    Glbertgmail:"Glbertjones001@gmail.com",
    date:"121-224-7890",
    addressTilte:"Address",
    wishList:"Wishlist",
    payment:"Payment",
    help:"Help",
    support:"Support",
    signOut:"Sign Out",
    address:"2715 Ash Dr. San Jose, South Dakota 83475",
    streetAddress:"Street Address",
    ShopCategories:"Shop by Categories",
    notification:"Notification",
    order:"Order",
    processing:"Processing",
    shipped:"Shipped",
    delivered:"Delivered",
    returned:"Returned",
    cancel:"Cancel",
    OrderNo:"Order  #456765"


}
export default AppStrings;
